server:
  port: 8089
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: test
    druid:
      filters: stat,wall
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 1
      validation-query: select 1
  h2:
    console:
      enabled: true
      path: /h2
  thymeleaf:
    cache: true
mybatis-plus:
  type-aliases-package: com.pho.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true